version: '3.8'

services:
  neo4j-hacking:
    image: neo4j:5.14.0
    container_name: neo4j-hacking
    ports:
      - "7475:7474"  # HTTP (Browser)
      - "7688:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/hacking_slm_2025
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

