version: '3.8'

services:
  neo4j-hacking:
    image: neo4j:5.15-community
    container_name: neo4j-hacking
    ports:
      - "7474:7474"  # HTTP (Browser)
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/domain_slm_2025
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    restart: unless-stopped

